// Auto-generated by deployment pipeline (placeholder for local/dev)
// Valores reales se inyectan desde GitHub Secrets durante el deploy.
// Mantener vacío en repo para evitar exponer credenciales.
window.OPENSEA_API_KEY = '';
window.OPENSEA_MCP_TOKEN = '';
window.OPENSEA_API_KEY_FALLBACK = '';
window.OPENSEA_COLLECTION_SLUG = '';

