// SPDX-License-Identifier: MIT
pragma solidity >=0.8.17;

/// AUTO-GENERATED by script/gen_data.py — DO NOT EDIT.
/// Combo row (ROW_BYTES = 10): [mode][punk][top][beard][hair][hat][mouth][eye][miscLo][miscHi]
/// mode & punk are 0-based; top..eye are 1-based (0=None); misc is a 12-bit mask.
library TigerMeta {
    uint256 internal constant SUPPLY = 10000;
    uint256 internal constant ROW_BYTES = 10;
    bytes32 internal constant PROVENANCE = 0x9fa2a02518b29e53663ce684b57e527f5772ba5606fd38f11083bc97222e173d;

    function labels_Mode() internal pure returns (string[5] memory) { string[5] memory a = ["Dark", "Light", "OG", "OG 107", "Tiger"]; return a; }
    function labels_Punk() internal pure returns (string[8] memory) { string[8] memory a = ["Adrian", "Alien", "Ape", "NPC", "Tiger", "White Tiger", "Zombie", "Lama"]; return a; }
    function labels_Top() internal pure returns (string[18] memory) { string[18] memory a = ["Black Polo", "Black Swearshirt", "Black T Shirt", "Blue Polo", "Bomber", "Bruce Lee", "Grand Master Flash", "Hoodie Blue", "Hoodie Red", "Hoodie", "MCD Polo", "Mankini", "Pink Polo", "Swearshirt", "Uniform", "White Polo", "White T Shirt", "Worker Vest"]; return a; }
    function labels_Beard() internal pure returns (string[10] memory) { string[10] memory a = ["Chinstrap", "Front Beard Dark", "Front Beard", "Goaty", "Handelbar", "Moustage", "Mutton Chops", "Normal Beard Black", "Normal Beard", "Shadow Beard"]; return a; }
    function labels_Hair() internal pure returns (string[30] memory) { string[30] memory a = ["Bob", "Crazy Hair", "Flat Top", "Long Hair", "Longer Hair Dark", "Longer Hair", "Mid", "Mohawk", "Normal Popper", "Popper", "Short", "Spike", "Tonsure", "Wild", "Crazy Blond", "Crazy Brown", "Crazy Green", "Long Brown", "Longer Blond", "Longer Brown", "Mid Blond", "Mid Brown", "Mohawk Green", "Mohawk Red", "Popper Blond", "Popper Brown", "Short Blond", "Short Brown", "Wild Blond", "Wild Brown"]; return a; }
    function labels_Hat() internal pure returns (string[23] memory) { string[23] memory a = ["Bandana", "Bunny", "Cap Backward", "Cap Foreward Blue", "Cap Foreward", "Cap Purple", "Cowboy Hat", "Crown", "Do rag", "Fedora", "G.I", "Head Band", "Headphones Black", "Headphones Red", "Hoodie", "MCD Cap", "Mic", "Pilot Helmet", "Police Cap", "Propeller Hat", "Tassle Hat", "Tiara", "Top Hat"]; return a; }
    function labels_Mouth() internal pure returns (string[8] memory) { string[8] memory a = ["Cigarett", "Joint", "Mask", "Pipe", "Rainbow", "Sad", "Smirk", "Vape"]; return a; }
    function labels_Eye() internal pure returns (string[28] memory) { string[28] memory a = ["3D Glasses Big", "3D Glasses", "3d Eyes", "Big Shades", "Blade Blue", "Blade Pink", "Classic Shades", "Eye Mask", "Eye Patch Left", "Eye Patch Right", "Eyes Left", "Eyes", "Golden Shades", "Googly Eyes", "Graucho", "Horned Rimmed Glasses", "Laser Eyes", "Monocle", "Nerd Glasses", "Pink Shades", "Pink Visor", "Pixel Glasses", "Regular Shades", "S.W.A.T. Goggles", "Ski Goggles", "Smol Shades", "VR", "Welding Goggles"]; return a; }
    function labels_Misc() internal pure returns (string[12] memory) { string[12] memory a = ["AirPod", "Choker", "Clown Nose", "Diamond Earring", "Drool", "Gold Chain", "Gold Earring", "Jason Mask", "Neck Tattoo", "Nose Bleed", "Snot", "Tiger Tattoo"]; return a; }
}
