# Configuración para GitHub Pages
# Este archivo permite que GitHub Pages sirva archivos estáticos

# Configuración básica
title: AdrianLAB - Retro Adventure DApp
description: Una dapp retro pixel art para la red BASE
url: "https://adriangallery.github.io/AL"

# Configuración de Jekyll
plugins:
  - jekyll-feed

# Configuración de GitHub Pages
github:
  is_project_page: true

# Configuración de archivos
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.svg"
  - "*.mp3"
  - "*.wav"
  - "*.ogg"
  - "*.json"
  - "*.txt"
  - "*.md"

# Excluir archivos
exclude:
  - "node_modules"
  - "*.log"
  - ".git"
  - ".github"
  - "README.md"
  - "LICENSE"
  - ".gitignore" 