// Auto-generated by GitHub Actions - DO NOT EDIT MANUALLY
window.SUPABASE_URL = 'https://scsxdqudvprtfikkepmu.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjc3hkcXVkdnBydGZpa2tlcG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MzM0NTUsImV4cCI6MjA3OTAwOTQ1NX0.0li2dAbyh5Ed4FjnZxxr63RSEPlWvsvZ923hBoK8YjY';
window.ALCHEMY_API_KEY = 'pqRmKgTaLqm2eak9iML1f';
