// Runtime configuration - DEVELOPMENT VERSION
// This file will be REPLACED during GitHub Actions deployment with secrets
// DO NOT commit your actual API key here

// For local development, set your API key here temporarily:
// window.ALCHEMY_API_KEY = 'your-key-here';

// For production, this is auto-generated by GitHub Actions from secrets
if (typeof window.ALCHEMY_API_KEY === 'undefined') {
  console.warn('⚠️ ALCHEMY_API_KEY not set. This file should be replaced during deployment.');
  console.warn('   For local development, add your key to this file temporarily.');
  window.ALCHEMY_API_KEY = '';
}
