// Auto-generated by GitHub Actions during deployment - DO NOT EDIT MANUALLY
// This file is generated from GitHub Secrets and should not contain hardcoded values
// Values are injected during deployment by GitHub Actions workflows
// Generated at: 2025-12-30 10:39:20 UTC
window.SUPABASE_URL = 'https://scsxdqudvprtfikkepmu.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjc3hkcXVkdnBydGZpa2tlcG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MzM0NTUsImV4cCI6MjA3OTAwOTQ1NX0.0li2dAbyh5Ed4FjnZxxr63RSEPlWvsvZ923hBoK8YjY';
window.ALCHEMY_API_KEY = '8jQ-SlSCz1OXmx_LVkMzq';
