// Auto-generated by GitHub Actions during deployment - DO NOT EDIT MANUALLY
// This file is generated from GitHub Secrets and should not contain hardcoded values
// Values are injected during deployment by GitHub Actions workflows
// For local development, these will be empty and the app will use fallbacks
window.SUPABASE_URL = '';
window.SUPABASE_ANON_KEY = '';
window.ALCHEMY_API_KEY = '';
